openapi: 3.0.0
info:
  title: TweetPrinter api documentation
  version: 1.0.0
  description: API documentation for tweet-printer-api project
servers:
  - url: http://localhost:3000

tags:
  - name: Orders
  - name: Images
  - name: Products

paths:
  /order/get-all:
    get:
      tags:
        - Orders
      summary: Retrieve a list of all orders
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Page number for pagination
      responses:
        200:
          description: A list of orders
          content:
            application/json:
              schema:
                type: object
                properties:
                  orders:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
                  currentPage:
                    type: integer
                  totalPages:
                    type: integer
                  totalOrders:
                    type: integer
        500:
          description: Failed to retrieve orders
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /order/create:
    post:
      tags:
        - Orders
      summary: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        200:
          description: Successfully created order
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                  paypalPending:
                    type: string
                  orderId:
                    type: string
        500:
          description: Failed to create order
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /order/update:
    patch:
      tags:
        - Orders
      summary: Update an order by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateOrderRequest'
      responses:
        200:
          description: Successfully updated order
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
        500:
          description: Failed to update order
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /order/complete-paypal-order:
    post:
      tags:
        - Orders
      summary: Complete a PayPal order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orderId:
                  type: string
      responses:
        200:
          description: Successfully completed PayPal order
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
        500:
          description: Failed to complete PayPal order
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /order/cancel-paypal-order:
    post:
      tags:
        - Orders
      summary: Cancel a PayPal order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paypalOrderId:
                  type: string
      responses:
        200:
          description: Successfully canceled PayPal order
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
        500:
          description: Failed to cancel PayPal order
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /image/generate:
    get:
      tags:
        - Images
      summary: Generate product image preview
      parameters:
        - in: query
          name: product
          schema:
            type: string
          description: Product name
        - in: query
          name: tweetUrl
          schema:
            type: string
          description: Tweet URL
        - in: query
          name: color
          schema:
            type: string
          description: Color of the product
        - in: query
          name: side
          schema:
            type: string
          description: Side of the product
      responses:
        200:
          description: Successfully generated image preview
          content:
            application/json:
              schema:
                type: object
                properties:
                  image:
                    type: string
                    format: base64
                  tweetImageBase64:
                    type: string
                    format: base64
                  pricePreview:
                    type: number
        500:
          description: Failed to generate image preview
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /product/get-all-images:
    get:
      tags:
        - Products
      summary: Retrieve all product images
      responses:
        200:
          description: Successfully retrieved all images
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Image'
        500:
          description: Failed to retrieve images
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  schemas:
    Order:
      type: object
      properties:
        name:
          type: string
        mobileNumber:
          type: string
        state:
          type: string
        city:
          type: string
        address:
          type: string
        shipping:
          type: string
        status:
          type: string
        payer:
          type: object
        paypalOrderId:
          type: string
        email:
          type: string
        total:
          type: number
        createdAt:
          type: string
          format: date-time
        note:
          type: string
        items:
          type: array
          items:
            type: object

    CreateOrderRequest:
      type: object
      properties:
        name:
          type: string
        mobileNumber:
          type: string
        state:
          type: string
        city:
          type: string
        address:
          type: string
        shipping:
          type: string
        email:
          type: string
        items:
          type: array
          items:
            type: object
            properties:
              product:
                type: string
              color:
                type: string
              tweetUrl:
                type: string

    UpdateOrderRequest:
      type: object
      properties:
        orderId:
          type: string
        status:
          type: string
        note:
          type: string

    Image:
      type: object
      properties:
        image:
          type: string
        tweetUrl:
          type: string
